print("Welcome to Band Name Generator.")
print("What's the name of the city you grew up in?")
city = input()
print("What's your pet's name?")
pet_name = input()
print(f"Your band name could be {city} {pet_name}")